version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--save", "20", "1",
      "--loglevel", "warning",
      "--requirepass", "${REDIS_PASSWORD}"
    ]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
